spring:
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为master
      primary: master
      #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        master:
          url: jdbc:mysql://192.168.10.128:3306/arkham?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8&useSSL=false
          username: arkham
          password: 123456arkham
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://192.168.10.129:3306/arkham?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8&useSSL=false
          username: arkham
          password: 123456arkham
          driver-class-name: com.mysql.cj.jdbc.Driver